### ISSUE TITLE
HTML conventions are not followed for h3

### ISSUE THREAD

**Issue by tbeu** [christiankral/KeyWordIO#2]
Modelica (Standard Library) convention: `In the HTML documentation of any Modelica library, the headings <h1>, <h2> and <h3> should not be used, because they are utilized by the automatically generated documentation.`

See corresponding MSL ticket https://trac.modelica.org/Modelica/ticket/1746. Since KeyWordIO depends on the MSL it might be useful to follow its conventions.

**Comment by christiankral** [comment]
Removed `<h3>` in actual master and v0.4.0
