### ISSUE TITLE
Possible infinite loop with fgetc

### ISSUE THREAD

**Issue by tbeu** [christiankral/KeyWordIO#4]
In C code of KeyWordIO/KeyWordIO/readLineWithoutCache.mo the `int` return value of `fgetc` is down-casted to `char` and then compared with `EOF`. This is bad coding and can lead to infinite loops on some platforms. See http://www.drpaulcarter.com/cs/common-c-errors.php#4.1 for more information and how to fix.

**Comment by tbeu** [comment]
Just checked with ModelicaInternal.c which does it right.

**Comment by tbeu** [comment]
This is fixed, right?

**Comment by AHaumer** [comment]
If I remember correctly, yes (11 months ago).
